import type { PageServerLoad } from './$types';

export const load: PageServerLoad = async () => {
	const questions = [
		{
			id: 1,
			text: "Which of the following best describes Newton's second law of motion?",
			type: "MCQ",
			correct: "B",
			subject: "Physics",
			exam: "JAMB",
			diff: "Medium",
			marks: 2,
			time: 60,
			year: "2022",
			explanation: "Newton's second law states F = ma.",
			img_url: null,
			bulk: false,
			date: "2024-03-12",
		},
		{
			id: 2,
			text: "The mitochondria is the powerhouse of the cell.",
			type: "T/F",
			correct: "True",
			subject: "Biology",
			exam: "WAEC",
			diff: "Easy",
			marks: 1,
			time: 30,
			year: "2021",
			explanation: "Mitochondria produce ATP through cellular respiration.",
			img_url: null,
			bulk: false,
			date: "2024-03-10",
		},
		{
			id: 3,
			text: "The largest planet in our solar system is ______.",
			type: "FIB",
			correct: "Jupiter",
			subject: "Biology",
			exam: "NECO",
			diff: "Easy",
			marks: 1,
			time: 45,
			year: "2020",
			explanation: "Jupiter is the largest planet by mass and volume.",
			img_url: null,
			bulk: false,
			date: "2024-03-08",
		},
		{
			id: 4,
			text: "Explain the causes and consequences of the Nigerian Civil War, focusing on political and economic factors.",
			type: "Theory",
			correct: "",
			subject: "History",
			exam: "WAEC",
			diff: "Hard",
			marks: 10,
			time: 300,
			year: "2019",
			explanation: "",
			img_url: null,
			bulk: false,
			date: "2024-03-05",
		},
		{
			id: 5,
			text: "Which gas is most abundant in the Earth's atmosphere?",
			type: "MCQ",
			correct: "C",
			subject: "Chemistry",
			exam: "JAMB",
			diff: "Easy",
			marks: 1,
			time: 45,
			year: "2023",
			explanation: "Nitrogen makes up about 78% of Earth's atmosphere.",
			img_url: null,
			bulk: false,
			date: "2024-03-01",
		},
	];

	const subjects = [
		"Mathematics",
		"English",
		"Biology",
		"Physics",
		"Chemistry",
		"Government",
		"History",
		"Geography",
		"Economics",
	];

	return {
		questions,
		subjects
	};
};
